### ISSUE TITLE
桂晓冬这个人

### ISSUE THREAD

**Issue by rabbitorange** [botorange/Welcome#1]
桂晓冬，男，安徽人，1993年11月生，天蝎座，未婚。_

研究生学历，毕业于北京第二外国语学院，汉语国际教育专业。

工作经历：    2017年7月—2018年5月，在泰国宋卡王子大学普吉孔子学院工作，
                       负责泰南HSK考试推广，汉语教学，文化活动等工作；
收获经验值：抗压能力和注重细节`

个人性格：      1， 乐于与人交流，善于沟通
                         2， 喜欢新鲜事物，不喜欢墨守成规，喜欢问为什么
                         3，做事肯坚持，但是自觉反应略慢，拖延症患者（目前在康复）
               
为何选择桔子：1，我想一探究竟互联网产品从诞生到连接用户等过程的运营；
                          2，据透漏，桔子的创始人们都是very nubility的人，让我心生向往；
                          3，我想在桔子这儿得到成长并对桔子的成长能够起到一些作用；
                          
前期工作计划：1，详细了解桔子的产品，学习相关的非技术人员必知的技术；
                           2，明确当下具体的工作任务及未来工作的发展方向。

**Comment by lijiarui** [comment]
已入职
