### ISSUE TITLE
下一代智能客服系统的思考

### ISSUE THREAD

**Issue by lzx9612** [botorange/Welcome#18]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：下一代智能客服系统的思考：随着大数据和人工智能的兴起，智能客服系统也必然会发展到更加智能，完善的层次。在下一代智能客服系统的发展上，我认为的发展方向：
（1）与用户交互层面  
1.知识量，数据量大。通过对大量案例的学习，进行更加拟人的回复，拒绝冰冷，模板回复；并且完善解决问题的能力，可以处理的问题种类更多，更全面。
2.对话内容不局限于一问一答。联系上下文，理解人类的语句中经常省略的部分，归类同一问题，结合问题群思考，知道，理解问题什么时候结束，并给出更加精确的回复。
3.在无法理解用户输入时，类似于输入法模糊拼音功能，在理解用户问题是自动联想用户可能想说的话，联系上下文，判断用户是否为输入错误，并且自动纠错。
4.在给出解决方案时，类似于地图导航或者飞机订票，计算最优路径，不只是给出用户所有解决方案，通过计算给出最优方案。
5,。更加智能的处理多媒体内容如图像，文字，声音等。
（2）商业层面
1.分析真人成功案例，学会商业营销对话模式，语句，技巧。
2.在进行实际操作时，自主通过大数据分析机器对话成功案例，进行聚类，针对不同类型目标用户进行不同引导，精准引流。
3.同样自主分析，学习失败案例，对话，减少错误率。
（3）技术层面
开发团队需要不断学习业内新技术，新理念，使得自己的产品更加实用化，智能化，轻量化。

**Comment by lijiarui** [comment]
已安排面试
