### ISSUE TITLE
对于下一代智能客服的思考

### ISSUE THREAD

**Issue by mayimayi2019** [botorange/Welcome#20]
期待你加入桔子互动！请将答案写在下面。
陈泽新
weareyuong@163.com
产品经理
用户操作简单，解决问题更加简单快捷
1)用户角度
1，	智能客服自我学习。 在用户与智能客服机器人对话过程中，机器人会根据用户的反 馈自主学习，调整对话策略和对 话结果，随着反馈的增多，机器 人理解用户意图会越来越精准。
2，	智能客服更加人性化。将检索到的信息用更生活化的语言讲述出来，这可以增加人与机器人的互动，提高用户体验感。
3，	高效整合各类电子渠道资源。支持网站、微信、微博、qq、移动应用、电话、短信、邮件等全渠道接入方式。
4，	强大的识别处理功能。对文字、语音、图像有更加强大的识别功能、处理功能，对用户提出的问题给出最优方案。
2)系统角度：
1,开发者应开放平台，让更多的人参与到开发中来，不断完善智能客服系统。
3)商业角度：
1,提高与企业实际业务的融合度。将用户和企业业务的数据进行关联，智能、精准的对用户进行优惠活动咨询、商品推荐、退换货处理、售后，以及营销等问题的处理

**Comment by lijiarui** [comment]
已安排面试
