### ISSUE TITLE
前端-王绍杰

### ISSUE THREAD

**Issue by wangshaojie1995** [botorange/Welcome#21]
期待你加入桔子互动！请将答案写在下面。

**Comment by lijiarui** [comment]
@wangshaojie1995 

1. 请使用开源项目wechaty（ https://github.com/chatie/wechaty ）搭建一个微信机器人，机器人功能可由你自定义，建议使用TypeScript 进行编写。
2. 搭建完成后，请新建一个github项目，并将项目地址写在这里：https://github.com/botorange/Welcome/issues/new 

完成以上两项才算完成笔试
