### ISSUE TITLE
对下一代智能客服系统的思考

### ISSUE THREAD

**Issue by Yaowei5** [botorange/Welcome#22]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
客服，通俗理解即企业通过文字或语音与客户沟通以解决客户需求的过程，可细分为售前客服和售后客服。售前客服重在引导客户了解产品，并实现成功转化；售后客服重在提高用户满意度。
当前市面上较主流的智能客服系统有阿里的“阿里小蜜”、京东的“无人客服”、网易的“七鱼“等，这些智能客服系统可以解决大部分常见的客服问题，但主要工作大部分限制在与客户的问答中，同时因自然语言的复杂性，机器人对客户语言的理解也经常会出现偏差。
未来智能客服有以下几个发展趋势：
1.	技术突破。人工智能技术进一步发展，机器的自然语言理解力提升，可以理解用户的不同表达方式，准确理解其意图；
2.	高度拟人化。机器人用语更为灵活多变，更拟人化，让用户没有意识到与机器人沟通，提高人机交互体验；
3.	具备营销能力。根据用户需求，做到智能精确推荐，并且通过深度学习营销方式，具备一定的营销能力，提升用户转化率；
4.	自我学习。在工作过程中对业务知识进行积累，协助管理人员修改、更新业务知识库，避免业务知识库的更新滞后性；
5.	服务多样。功能不局限在问答层面，而是更为多样，包括购买、商品推荐、退换等用户操作的一站式服务，通过人机语言交互即可直接完成相关功能流程。

**Comment by lijiarui** [comment]
已发面试邀请
