### ISSUE TITLE
产品经理岗位笔试回答

### ISSUE THREAD

**Issue by Brand77** [botorange/Welcome#24]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：

下个版本的战略方向不敢说，但对于产品本身来说一下个人的体验和思考

1. 个人试用后，认为产品本身属于封装的客服IM属性服务程序，但对于B端的机器人回复的消息，需要商家重新梳理客服正常工作流程中的常用语，就会增加商家将机器人投入使用的时间成本，建议将通用类的回复语同程序打包发送使用，而后客户根据公司需求进行少量调整。(需要数据支持论断)

2.看之前的回答后思考了一下，无论编程角度，还是当下语言程度，都无法达到完美的人机语言交互的完美，因为那需要大内存和重复运算的资源浪费，不妨使用"斗图""表情包"的旧概念新作。
这就从用户体验角度解决了机器人的无感情语言的不足之处，并且当下技术可初步实现。(根据互联网AI市场走向得出结论)

3.以往的运营经验中，客户经理的微信对于老客户和久久不联系的有签单意向客户，需要周期性PC数据复盘，并且整合后回访，增大了工作重复性，降低了效率。
而机器人可以尝试增添一个设置时间提醒客户经理的信息功能(也可以尝试提醒客户)，从而解决这个诉求。
(由于试用期间未找到此功能，且这个是以往经验的主观臆断，拍脑袋想出来的，如果见解不对请忽略此条。)

**Comment by lijiarui** [comment]
已发笔试邀请
