### ISSUE TITLE
笔试

### ISSUE THREAD

**Issue by ZhangJinda96** [botorange/Welcome#25]
期待你加入桔子互动！请将答案写在下面。

#### 你的姓名：
张金达
#### 你的邮箱：
zhangjinda96@163.com
#### 你面试的岗位：
产品经理
#### 你的答案：

以下为思考过程简述：
竞品选择：奥创、wetool、米云客服
本次调研的管理系统主要是通过智能客服帮助企业快速获客，增加用户粘性并提高转化，通过简单对比分析下一代客服系统的方向。
企业需求：高效、低成本的解决用户问题
用户需求：更精准的、更快速的得到答案
需要解决的问题：
高效管理、及时反馈用户诉求、精准问题解决
未来规划：
机器人自动高效回复，问题精准度匹配，自定义客户标签，采取精细化运营策略

**Comment by lijiarui** [comment]
已安排面试
