### ISSUE TITLE
陈彦伊 产品助理 18331567356

### ISSUE THREAD

**Issue by cyy1111** [botorange/Welcome#26]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
通过我的对产品免费的初步体验提出以下优化建议

体验设备环境：Windows

入口：公司官网免费体验

1.【在线聊天】模块有缓存延迟，一些时间久远的会在聊天列表在顶部出现；聊天列表中还会出现一些公众号；
2.【基础设置】模块中【好友管理】中”在聊天列表中已删除的好友“”黑名单中删除的好友“仍然会显示在”好友列表“中。建议添加二级列表，细化分类管理好友数据；【群管理】中仍然存在一些无效群的痕迹，并且在管理端并不能删除并退出这些无效群，建议添加删除退出无效的群功能
3.由于没有企业运营环境体验针对【消息群发】【关键词入群】【自动回复】模块，暂时没有优化建议。
4.在网页端扫码登录微信后，在手机微信端会提示“ipad端登录微信”并且出现微信pc端掉线的情况。

**Comment by lijiarui** [comment]
已安排面试
