### ISSUE TITLE
对下一代智能客服系统的思考

### ISSUE THREAD

**Issue by 592230017** [botorange/Welcome#27]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
对下一代智能客服系统的思考：
**问题按照两个维度拆解：系统本身的功能与业务逻辑需求的额外功能**

一、系统本身的功能
    1.数据搜集与分析能力。不能仅仅局限于简单的一问一答人机对话，分析用户数据，挖掘用户画像能为B端企业提供更为有力的数据支撑，优化决策。（竞品小U管家和微友助手提供了数据分析的能力）
    2.多渠道多号在多端进行管理。多渠道指小程序、公众号、个人号。多号指有好几个微信号，公众号，小程序。多端管理是指在PC网页端，手机小程序端都可以快捷的进行消息同步。（多端的优先级稍微排后面一点，需求优先级没有那么高）。
    3.机器人拟人化。这个概念可能比较抽象，大概就是要求机器人有性格、故事、各自的特点，企业主可以根据自己的需求进行设定选择。人格化的机器人可以为企业营销，用户转化提供一些契机。

二、业务逻辑需求的额外功能
    1.行业增值服务。明确我们的产品所要服务的行业领域，对于企业本身的业务需求进行挖掘，针对性的设计功能，并且将这些功能也可以复用到同行业的其他公司上，便于推广。
    2.延展服务——品牌/产品营销。机器人所能提供的服务，在各个竞品之间都将是趋同的，那么我们需要两条腿走路，一条是硬实力——系统的功能、交互、准确率；另一条是软实力——系统的外延给消费者带来的吸引力与趣味。
    3.基于行业增值服务的工具/数据报表

三、竞品对比
以下是我对竞品功能的小分析，0表示无，1表示有

产品     功能 | 小U管家企业版 | WeTool | 微友助手 | 桔子互动
-- | -- | -- | -- | --
入群欢迎 | 1 | 1 | 1 | 1
自动回复 | 1 | 1 | 1 | 1
定时群发 | 1 | 1 | 1 | 0
即时群发 | 1 | 1 | 1 | 1
一键收藏 | 1 | 0 | 0 | 0
消息汇总 | 1 | 1 | 1 | 1
扫码入群 | 1 | 1 | 0 | 0
标签入群 | 1 | 1 | 1 | 1
群分组 | 1 | 1 | 1 | 1
广告监控 | 1 | 1 | 1 | 0
数据统计 | 1 | 1 | 1 | 1
群明细 | 1 | 1 | 1 | 0
素材库 | 1 | 0 | 0 | 1
发票管理 | 1 | 0 | 0 | 0
员工名单 | 1 | 0 | 0 | 0
个人中心 | 1 | 0 | 0 | 0
群明细 | 1 | 1 | 0 | 0
助手设置（开群数，个性化助手等） | 1 | 1 | 1 | 1
直播 | 1 | 0 | 0 | 1
客服数据呈现 | 1 | 0 | 0 | 0
工作状态监督 | 1 | 0 | 0 | 0
客户画像 | 1 | 0 | 1 | 1
客户咨询明细分类 | 1 | 0 | 0 | 0
支持多端登录 | 1 | 0 | 0 | 0
多渠道消息接入（小程序、公众号、个人号） | 1 | 0 | 0 | 0
所有微信号进行管理 | 0 | 1 | 0 | 0
批量加好友 | 0 | 1 | 0 | 0
好友去重 | 0 | 1 | 0 | 0
僵尸粉检测与清理 | 0 | 1 | 1 | 0
发红包提醒 | 0 | 0 | 1 | 0
入群暗号 | 0 | 0 | 0 | 1

    根据以上表格得知，有部分基础功能还需要陆续加入（批量加好友、多账号管理等）。
四、感想
1.我认为一个好的产品，就需要赋予它一个感情，哪怕它是一种工具。
2.想办法调动企业主的感情，让他们知道，使用我们的系统就能看到未来。
3.消费者会对新的事物产生好奇，放大这个好奇心与吸引力，让他们感觉到有趣味，而不是在走流程做交易。

五、致谢
感谢您能给我一个机会去整理这一份小作业，这几天也花了不少时间充实知识。
由于发烧了好几天时间可能稍有仓促，望见谅！
望有幸取得面试机会，感谢。

**Comment by lijiarui** [comment]
已安排面试
