### ISSUE TITLE
张子淳 产品经理笔试

### ISSUE THREAD

**Issue by pollyxyx** [botorange/Welcome#28]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
1.现有一部分机器客服并不能识别较难句型，例如询问如何领取积分（或领取积分方法），只能识别（回答）积分的用处，有点所答非所问。（在客户潜意识里，认为机器客服并不靠谱，愿意直接选择人工客服解决）
2.还有一部分机器客服只能回答特定语句，并不能回答客户问题。
3.机器转人工客服等待时间过长，且机器客服不能解决问题，导致客户放弃产品。（其中有些淘宝店并没有客服）
4.前景：基础问题可以直接通过智能客服解决，节省人工成本，降低客户在等待人工客服接线中所产生的火气；我认为微商使用前景大，客户下单、接单和报价可以智能解决，减少客户等待时间，和商户自身回复同一消息的重复率；要提高智能机器客服的业务开展的信用率，使更多的人能够在第一时间先选择机器客服解决问题。

**Comment by lijiarui** [comment]
已发面试邀请
