### ISSUE TITLE
下一代智能客服系统的思考

### ISSUE THREAD

**Issue by b541227688** [botorange/Welcome#29]
期待你加入桔子互动！请将答案写在下面。

你的姓名：暴庭轩

你的邮箱：13003827219@163.com

你面试的岗位：产品经理

你的答案：
         智能客服系统是在大规模知识处理基础上发展起来的一项面向行业应用的，适用大规模知识处理、自然语言理解、知识管理、自动问答系统、推理等等技术行业，智能客服不仅为企业提供了细粒度知识管理技术，还为企业与海量用户之间的沟通建立了一种基于自然语言的快捷有效的技术手段；同时还能够为企业提供精细化管理所需的统计分析信息。而我认为下一代智能客服系统主要从以下几个方面来提升：

1.从行业能力来看：未来的智能客服系统，需要很好的技术能力如：并发能力，系统架构，安全能力，决定了一家公司的智能服务系统是否好用，并发能力是看系统中能稳健的服务和跑的客户数量来确定它的稳定性。系统架构就是要有多个版本来供客户去选择，对整体客户给予一个相同的基础，在对客户的特殊要求进行分别设计。安全能力是为了表现此系统的可靠性。

2.从产品能力来看：首先要满足销售中售前，售中，售后的一些基本能力，还要需要拓宽全面的渠道，不光是微信，网页，app传统的渠道，还要加上微博等辅助渠道，达到一个全渠道多方向的。
对于不同的客户要有精准和全面的记录客户画像,如地域，性别，年龄，脾气，关注什么产品，
一些习惯，不断的优化补充并对客户进行分类，在未来才能提前了解，精准服务，对合适的人群二次推销。对数据方面，需要有更多数据进行优化处理，所以要存储和更新的数据集合需要很大一部分，还要合理优化每个数据并且使之进行连接。

3.从服务能力来看，要有很优化的问题响应时间，以满足客户需要的结果。还有产品升级的时间，迭代的速度更快，能更高效的解决客户当前面临产品缺失的服务项目，还有客户成功体系，要让顾客有觉得产品帮助他们能高效的完成对企业客户的服务，还有一个完善的培训体系，让客户能觉得产品不是很复杂，能快速上手使用，能及时解答产品的使用问题。

**Comment by lijiarui** [comment]
已发面试邀请
