### ISSUE TITLE
自我介绍

### ISSUE THREAD

**Issue by ningtao3182** [botorange/Welcome#3]
宁涛，男，河北唐山人，1994年5月1日生，金牛座，未婚。本科学历，毕业于河北工业大学网络工程专业。联系方式：17801565400。
       工作经历：2017.9-2018.1，曾在首都在线实习，在一线运维部担任一线运维工程师的职位，负责查看公司云设备的监控报警等工作。
       个人性格：1.乐观开朗，善于沟通，自信向上，抗压能力强。
                         2.做事认真负责，有责任心，能按时按量完成任务。
                         3.勇于创新，敢于尝试新鲜事物，对生活充满激情向往。
       选择桔子；我认为桔子作为一个创业型公司它的发展前景我比较看好，而且我认为我适合这份工作，不仅能够让我在工作中得到成长，同样也可以让我为公司实现发展收益。

**Comment by lijiarui** [comment]
已入职
