### ISSUE TITLE
徐浩严 产品经理笔试 15979188250

### ISSUE THREAD

**Issue by xuhaoyan123** [botorange/Welcome#30]
期待你加入桔子互动！请将答案写在下面。

#### 你的姓名：
徐浩严
#### 你的邮箱：
367075397@qq.com
#### 你面试的岗位：
产品经理
#### 你的答案：
对下一代智能客服系统的思考如下：

1.下一代智能客服应用领域
金融、保险、教育、零售、健康、政府服务、公共事业、交通物流、企业服务等。

2.市场分析
2.1 人工客服的减少
许多大企业表示，越来越多的年轻人不愿意再当客服了，而年龄较高的群体又很难处理重要且紧急的事情，所以人工客服的供给
量在减少，而客服服务的需求在增多。
2.2 人工客服的质量参差不齐难以管理
在我咨询一些下游厂商或者购买商品的时候，往往会遇到一些态度恶劣的客服，在遇到这类很不耐烦且脾气不好的客服的时候，会消减甚至
抹灭我的合作及购买意向。
2.3 人工客服的处理效率低下
对于前断时间滴滴的事件来说，客服的处理效率与这些事故不好的结果有着很大的关系，传统的人工处理的方式往往需要走很多流程，但是
找客服的用户一般都希望能立即处理眼前问题。
2.4 对服务高质量的需求
大家对政府的服务质量也提出了很高的要求，政府也在从传统的人工客服向智能客服的转变。
2.5 4小时服务的需求
许多企业期望提供24小时的咨询服务，可是一来成本太高，二来一些特殊时间段很难保证服务人员的充足以及服务质量的满意。

3.使用场景
3.1遇到紧急的事情，想要快速解决问题
3.2遇到人工客服回答不一定准确的问题
3.3中高端群体，想要高质量的服务
3.4特殊时间段想要类似人工的服务
3.5没有具体的目的，想了解全面的服务

4.当下智能客服痛点
4.1智能客服无法回答某些问题
有许多仅通过字意和语义缺分析不了的问题，需要人工进行回答。
4.2智能客服的知识面不全
需要不断给向智能客服喂养数据，智能客服无法主动获得数据，以至于智能客服的知识面局限于目前已有的知识。
4.3智能客服的回答过于官方
智能客服往往通过数据分类检索去获取答案，无法真正地做到自然语言处理的效果，回答的内容往往过于空洞官方，
缺乏场景化的思维和人情味。
4.4智能客服很难引导用户解决问题
智能客服很难主动向客户提出客户关心的问题，并无法引导客户去解决一个问题。

5.下一代智能客服发展方向
5.1应实现人机互动
当使用智能客服的时，要能够进行人机切换，遇到AI回答不了或者回答的结果不确定的时候切换到人工客服进行回答，
当人工客服知识量不够或者需要深度检索数据库才能回答的时候切换到AI进行回答。
5.2让智能客服自主学习
随着新数据的产生以及知识的更新，智能客服的学习是一个重要且持续不断的过程，长期靠人工去给AI填充知识不仅费时费力
还完整度不高。在下一代智能客服系统中我们需要让AI去自主学习，对于高频率且类似的问题，应该让AI结合场景和业务知识去
学习和积累，使知识不断丰富。
5.3提供场景化的人情服务
在实现智能客服对话过程中，我们应该结合更多的场景，提升对话的人情趣味，让用户在使用智能客服的过程中感觉不到是与机器人在对话，
而是真实地结合问题及对话的场景去进行人机交互，让机器人能像人一样充满趣味及人文关怀。
5.4从回答问题转变为引导用户解决问题
人们在开场时需要一个恰当的指导，智能客服应该适时对用户做引导，把用户引导到问题的解决上，而不是一直处于对话当中。
通过智能客服去引导用户自主逐步地解决问题，避免反复转入人工。让智能客服引导用户解决问题，使智能客服成为一名具备不
同技能的专业客服，能够自主去按流程、规范、制度解决用户的各类问题。

**Comment by lijiarui** [comment]
已安排面试
