### ISSUE TITLE
智能客服系统思考（张顺）

### ISSUE THREAD

**Issue by xiaorenguo** [botorange/Welcome#31]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
一、	目标用户
企业的目标用户

二、	目标客户
有客服管理需求的不同行业的企业机构，如教育，券商，保险，微商，餐饮等行业。

三、	场景逻辑
站在客户角度，从一件商品或一项服务的生命周期来看主要包含以下几个环节：
1.	营销（拉新）：广告触达，唤醒用户关注
2.	售前（留存）：用户全面感知服务特性，解决购买决策疑问
3.	销售（转化）：利益博弈平衡，达成交易
4.	售后（口碑）：过程跟踪，好评/问题上报，维护品牌/质保维修，口碑传播
5.	升级（循环）：需求整合，迭代升级，二次购买

       五大场景，从传统的角度，售后是非常依赖客服这块，但这个环节并不能够产生利润，也无法贡献需求价值，因此通常情况下这个版块的并没有支撑太大的价值，在所有职能板块里略微显得比较鸡肋。
       但如果从整体上，从释放客服在客户需求、产品问题和产品特性等层面的数据资源能力的角度来看，客服可以全面支撑营销、售前、销售、以及升级等场景的赋能。

四、	基本问题
A.	用户：
1.	无法快速感知核心服务的亮点（营销）
2.	无法快速和全面感知到能打动我的独特亮点（售前）
3.	无法快速的获取我想要的服务（销售）
4.	产品跟服务出问题的时候，解决问题的态度让人不满意，同时效率比较低（售后）

B.	客户：
1.	无法快速的了解用户的需求到底是什么。（售前）
2.	客服培训成本高，人力成本高，带来不了实际的转化价值，并且部门协同响应慢，无法提高较高的衍生价值。（售后）
3.	不能持续并且大规模的沉淀需求，以用于改进现有业务。（升级）

五、	核心价值
A.	企业外：
1.	捕捉需求，精准传达，提高转化
2.	系统联动，主动响应，尖叫服务

B.	企业内：
1.	统一知识，节省人力，降低成本
2.	沉淀数据，整合需求，优化业务

六、	产品逻辑
1.	挖掘用户需求
通过语音，图像或纯文字对话，以更加自然的交互形态成为全新的入口，快速而又全面地捕获用户的语言或肢体语言，同时对语言进行量化分析，从而挖掘用户需求。
2.	解决客户疑问
基于面向行业和业务的知识图谱，通过贴近人表达习惯与方式的语言表达模型，配合人机协同的方式，实现一对多的个性化讲解。
3.	满足客户需求
当需要某种特定任务而不仅仅是问答时，通过协同其他业务子系统，如工单系统，CRM，ERP等方式调动企业资源来解决问题满足用户需求。
4.	持续满足需求
基于语言问答和实际解决问题的案例，帮助企业归纳出所面临市场用户的共性需求，以用于业务改造升级。

七、	服务版块
1.	机器人问答系统
2.	机器人观测系统
3.	知识图谱及策略构建工具
4.	服务流程监控（拉新，留存，转化，持续留存，二次传播拉新）
5.	人机协作机制
6.	关联系统接口
7.	需求整合工具

八、	产品本质
企业组织的神经中枢

九、	关键变量
A.	技术层：
云计算，大数据，AI，5G，物联网

B.	硬件层：
智能手机，智能硬件

C.	平台层：
微信，UNIT，APP

D.	交互感知层：
鼠标/键盘，触摸屏，语音，图像

十、	产品形态
综上，产品形态的演变可以从场景跟技术两个维度进行衡量
A.	场景维度：
1.	售后客服：基于售后场景，被动接受客服反馈的客服问答，协同工单进行处理，提供局    
部质保维修，为个别企业的社会或法律风险负责。
2.	售前售后客服：支撑售前，销售跟售后环节，支撑留存，转化和口碑传播，为业绩增长
负责。
3.	全生命周期客服：全面赋能营销，售前，销售，售后和升级5大场景，为业务的整体发
展负责。

B.	技术维度：
1.	在线客服：依托电话跟互联网，进行在线一对一的人工客服服务。 
2.	自动客服：依托云计算，大数据和AI技术，基于语音和图像技术底层架构自然语言和
知识图谱技术完成一对多的拟人化高效率的交互。
3.	智能客服：依托5G跟物联网，实现极速传输跟万物感知，与人类共生，解决问题于无
形。

十一、	产品阶段
基于产品形态，可进一步将产品阶段划分为保障型，进取型和全能型三个阶段。
1.	保障型客服阶段：售后客服+在线客户
涉及服务版块有，电话，IM，云计算，人工坐席。
场景局限于售后。

2.	进取型客服阶段：售前售后客服+自动客服
涉及服务版块有，在1的基础上，增加机器人问答系统，知识图谱及策略构建工具，服务流程监控，人机协作机制，关联系统接口
场景拓展至售前和销售。

3.	全能型客服阶段：全生命周期客服+智能客服
涉及系统版块有，在2的基础上，增加机器人观测系统，需求整合工具。
场景拓展至营销和业务升级。

**Comment by lijiarui** [comment]
已发送笔试邀请
