### ISSUE TITLE
关于下一代智能客服系统的建议和看法

### ISSUE THREAD

**Issue by 201524090230sd** [botorange/Welcome#32]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：在发表自己建议之前，我尝试免费注册使用了贵公司的智能机器人，以下仅代表个人观点:
1.智能机器人首先是解决企业运营工作人员的重复性工作，这是刚需，我觉得基础功能应该持续打磨，通过调查问卷明确哪些需求可以优化。
2.智能机器人要表现的人性化，交流能幽默些，让顾客感觉亲切些。
3.智能机器人通过背后的技术支持更加专业化，算法深度学习，通过关键字检索在数据库比对引导用户在智能机器人的引导下完成问题的解决，进一步解放企业的人力资源。

**Comment by lijiarui** [comment]
已安排面试
