### ISSUE TITLE
刘宇鹏   产品经理笔试  15935155171

### ISSUE THREAD

**Issue by SuDo-SmallLiu** [botorange/Welcome#34]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
在了解桔子互动后，我产生了以下想法：
我们假设一下，如果使用的客户主体是一个60岁左右的中年人（个体户），那么他是否会对我们的产品感兴趣呢？
很大可能他是不擅长使用这个东西的，所以主动性交互就变的尤为关键，在咨询10086的时候人们尝试无法解决问题后，为什么会去找人工客服呢？因为人工客服更灵活、更懂得用户需求更可以一键式解决客户的问题

那么我们的系统针对个人用户，可以做到一键式吗？
针对60岁左右的老人，可以做到正常的交互引导吗？

这需要更多的测试，也需要更多的变通。

我们的产品是核心是辅助管理功能，那么有没有考虑到售后的问题？相对人而言，工具可以更便捷的将数据统计、备份、存储及记录，但也造成了一个正常的问题，数据量大，普通人现在1年左右可以积累10个G左右的聊天记录，那么如果使用我们的工具，能否辅助判断客户进行清理？
甚至像人一样，记录关键点，从而减少数据量呢？

一个工具的顺手程度，决定了这个工具的使用时长，我想针对中老年客户也是我们产品发展的一个方向。

**Comment by lijiarui** [comment]
已发面试邀请
