### ISSUE TITLE
下一代智能客服系统的思考

### ISSUE THREAD

**Issue by YiWang1231** [botorange/Welcome#35]
期待你加入桔子互动！请将答案写在下面。

##### 目标
* 挖掘客户需求，加强与客户之间的联系，提高服务质量，再提升用户体验的同时，在用户心中建立良好的品牌形象，提高公司的综合竞争力，提升客户购买转化率
##### 客服现状
* 电话实时沟通
	* 痛点
		1. 排队，电话沟通无法随时连接，无法提供相关的文件描述，只能通过口头的形式沟通
		2. 多次沟通面对不同的客服需要将问题不断重述
* IM半自动化客服：类似淘宝，JD，预设一些问题，用户输入关键字后通过选择选择对应的问题，系统回答相应的答案，也可以选择人工介入
	* 痛点
		1. 缺少一点温暖的感觉，过于冰冷
		2. 需要排队，不能及时回复客户
		3. 无法定位用户的需求，需要用户自行描述
		4. 应变能力较差，人工介入比例较高
		5. 没有对用户的问题及需求行为进行记录，形成后续的数据支撑
##### 新一代智能客服
* 一定要加入AI元素
* 一定要加入大数据的支撑
###### 如何实施
1. 用户进入产品初期，机器人添加好友，根据注册信息，辅助信息（性别，城市，渠道），建立初步的用户画像，根据相似用户的喜好，确定初步的沟通方案，通过初步沟通方案不断完善用户画像
2. 不断的收集用户问题，形成巨大的数据源，和用户画像进行匹配，对问题赋权，方便以后对用户提问的问题列表进行排序，提升问题匹配的准确度
3. 不断收集用户的行为习惯，然后将用户画像进行不断的迭代优化
4. 根据用户画像结合环境因素，决定主动和用户沟通的时间，语气，以及向用户推荐的产品

**Comment by lijiarui** [comment]
已发面试邀请
