### ISSUE TITLE
对下一代智能客服系统的思考-lichao

### ISSUE THREAD

**Issue by ashes0129** [botorange/Welcome#36]
期待你加入桔子互动！请将答案写在下面。

#### 你的答案：
通过注册使用桔子互动后对下一代客服系统的思考：
1.下一代智能客服系统可以在交互前端接入领域语料训练的语音识别能力的智能客服机器人，添加语音和多媒体信息，成为一种智能IVR机器人。
2.下一代智能客服系统可以应该向着人机互动的全渠道整合应用方向发展。
3.下一代智能客服系统对企业所在行业进行精准划分，利用聚集效应和大数据的支撑来更高效、精确、及时的解决企业的问题以及满足企业的客户的需求（即更好的服务客户的客户，企业客服的宗旨就是服务企业的客户）。

**Comment by lijiarui** [comment]
已发笔试邀请

**Comment by ashes0129** [comment]
您好，我是今天下午来面试的李超同学，你们的hr电话没打通，我现在就在一楼大厅。




| |
ashes0129
邮箱：ashes0129@163.com
|

Signature is customized by Netease Mail Master

在2019年05月02日 15:18，lijiarui 写道：

已发笔试邀请
